import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import getConfig from "next/config";
import sbom from "@/models/sbom";
import { FilterSbom, FormatSBOMName } from "@/utils/Formating";
import {
  DownloadSBOMsFromMongoDB,
  UploadVulnToMongoDB,
} from "@/utils/mongoDBQueries";
import { DownloadSBOMFromGithub, DownloadVulnFromGithub } from "@/utils/github";

import { StubbyDependencyTree } from "@/utils/DependencyTreeStubyPackages";
import { FullDependencyTree } from "@/utils/FullDependencyTree";
import { OnlyUniqueDependencyTree } from "@/utils/OnylUniqueDependencyTree";
import {
  FullCSV,
  SBOMSWithPackageNameCSV,
  SBOMSWithoutPackageNameCSV,
} from "@/utils/csv";
import SecurityAdvisory from "@/models/vuln";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { publicRuntimeConfig } = getConfig();
  const [sboms, setSboms] = useState<sbom[]>();
  const ResetPackages = async () => {
    const sbom = await DownloadSBOMFromGithub("kubernetes", "Kubernetes");
    const uniquePackageNames = FilterSbom(sbom);
    const res = await fetch(
      publicRuntimeConfig.API_ENDPOINT + "/package/create",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(uniquePackageNames),
      }
    );
  };

  async function asd1() {
    const sboms: sbom[] = await DownloadSBOMsFromMongoDB();
    console.log("sboms set");
    setSboms(sboms);
  }
  const asd = async () => {
    for (let i = 0; i < sboms!.length; i++) {
      const formattedName = FormatSBOMName(sboms![i].name);
      const vulns: SecurityAdvisory[] = await DownloadVulnFromGithub(
        formattedName
      );
      for (let i = 0; i < vulns.length; i++) {
        await UploadVulnToMongoDB(vulns[i]);
      }
    }
  };

  const asd2 = async () => {
    const vulns: SecurityAdvisory[] = await DownloadVulnFromGithub([
      "as",
      "asd",
    ]);
    console.log(vulns);
    for (let i = 0; i < vulns.length; i++) {
      await UploadVulnToMongoDB(vulns[i]);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          Full Dependency Tree
          <button onClick={FullDependencyTree}>Full Dependency Tree </button>
          <button onClick={OnlyUniqueDependencyTree}>
            Only Unique Dependency Tree
          </button>
          <button onClick={StubbyDependencyTree}>Stubby Dependency Tree</button>
          <button onClick={FullCSV}>
            Download Every SBOM ONLY Once From DB
          </button>
          <button onClick={SBOMSWithPackageNameCSV}>
            Download Every SBOM ONLY Once From DB Ligth version
          </button>
          <button onClick={SBOMSWithoutPackageNameCSV}>
            Download Every SBOM ONLY Once From DB Ligth version Without
            PackageNames
          </button>
        </div>
        <button onClick={asd1}>SBOMS</button>
        <button onClick={asd}>IssuesTest</button>
      </main>
    </>
  );
}
