import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import getConfig from 'next/config'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { publicRuntimeConfig } = getConfig();
  const [data, setData] = useState();
  useEffect(() => {
    const fetchData = async () => {
        try {
          const resData = await fetch(publicRuntimeConfig.API_ENDPOINT + "/kubernetes");
           const dataSBOM = await resData.json();
          setData(dataSBOM);
        } catch (error) {
          console.error("Error fetching data:", error);
        }
    };

    fetchData();
  }, []);


  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      </main>
    </>
  )
}
